// Code generated by protoc-gen-go. DO NOT EDIT.
// source: myc/protocol/gossip.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import version "gitlab.com/SporeDB/sporedb/db/version"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hello struct {
	Version   uint64                     `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Identity  string                     `protobuf:"bytes,2,opt,name=identity" json:"identity,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// The public key is used in the ECDHE key exchange.
	// It MUST be a curve25519 public key.
	PublicKey []byte `protobuf:"bytes,9,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// The signature of the Hello message is computed on the message with an empty signature.
	// signature = signature by emitter ( marshal ( hello without signature ) )
	//
	// It is used as the authentication block of the ECDHE key exchange.
	// If the used signature key is not trusted by one peer, the connection MAY BE established
	// in "untrusted" mode, meaning that sensible operations MUST NOT be executed with the
	// connected peer (vulnerable to MitM attacks).
	Signature []byte `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Hello) Reset()                    { *m = Hello{} }
func (m *Hello) String() string            { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()               {}
func (*Hello) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Hello) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Hello) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Hello) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Hello) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Hello) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Raw struct {
	Key       string     `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Version   *version.V `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Data      []byte     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Signature []byte     `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Raw) Reset()                    { *m = Raw{} }
func (m *Raw) String() string            { return proto.CompactTextString(m) }
func (*Raw) ProtoMessage()               {}
func (*Raw) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Raw) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Raw) GetVersion() *version.V {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Raw) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Raw) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Node struct {
	Identity string `protobuf:"bytes,1,opt,name=identity" json:"identity,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Node) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Nodes struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *Nodes) Reset()                    { *m = Nodes{} }
func (m *Nodes) String() string            { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()               {}
func (*Nodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Nodes) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Gossip struct {
	Spores  []string `protobuf:"bytes,1,rep,name=spores" json:"spores,omitempty"`
	Request bool     `protobuf:"varint,2,opt,name=request" json:"request,omitempty"`
}

func (m *Gossip) Reset()                    { *m = Gossip{} }
func (m *Gossip) String() string            { return proto.CompactTextString(m) }
func (*Gossip) ProtoMessage()               {}
func (*Gossip) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Gossip) GetSpores() []string {
	if m != nil {
		return m.Spores
	}
	return nil
}

func (m *Gossip) GetRequest() bool {
	if m != nil {
		return m.Request
	}
	return false
}

func init() {
	proto.RegisterType((*Hello)(nil), "protocol.Hello")
	proto.RegisterType((*Raw)(nil), "protocol.Raw")
	proto.RegisterType((*Node)(nil), "protocol.Node")
	proto.RegisterType((*Nodes)(nil), "protocol.Nodes")
	proto.RegisterType((*Gossip)(nil), "protocol.Gossip")
}

func init() { proto.RegisterFile("myc/protocol/gossip.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x4f, 0x4b, 0xfc, 0x30,
	0x10, 0x25, 0xdb, 0xfd, 0xd7, 0xd9, 0xe5, 0xc7, 0x8f, 0x1c, 0x24, 0x16, 0xc5, 0x52, 0xf6, 0xd0,
	0x8b, 0x29, 0xac, 0x17, 0x11, 0xef, 0x0a, 0x82, 0x87, 0x20, 0x5e, 0xa5, 0xdd, 0x8e, 0x25, 0xd8,
	0x6d, 0x6a, 0x93, 0x2a, 0xfd, 0x5e, 0x7e, 0x40, 0x69, 0xda, 0xec, 0xa2, 0x17, 0x4f, 0x9d, 0x37,
	0xef, 0x4d, 0xdf, 0x9b, 0x09, 0x9c, 0xee, 0xbb, 0x5d, 0x52, 0x37, 0xca, 0xa8, 0x9d, 0x2a, 0x93,
	0x42, 0x69, 0x2d, 0x6b, 0x6e, 0x31, 0x5d, 0xba, 0x76, 0x70, 0x51, 0x28, 0x55, 0x94, 0x38, 0xe8,
	0xb2, 0xf6, 0x35, 0x31, 0x72, 0x8f, 0xda, 0xa4, 0xfb, 0x51, 0x1a, 0xb0, 0x3c, 0x4b, 0x3e, 0xb0,
	0xd1, 0x52, 0x55, 0xee, 0x3b, 0x30, 0xd1, 0x17, 0x81, 0xd9, 0x3d, 0x96, 0xa5, 0xa2, 0x0c, 0x16,
	0x23, 0xc5, 0x48, 0x48, 0xe2, 0xa9, 0x70, 0x90, 0x06, 0xb0, 0x94, 0x39, 0x56, 0x46, 0x9a, 0x8e,
	0x4d, 0x42, 0x12, 0xfb, 0xe2, 0x80, 0xe9, 0x35, 0xf8, 0x07, 0x33, 0xe6, 0x85, 0x24, 0x5e, 0x6d,
	0x03, 0x3e, 0xc4, 0xe1, 0x2e, 0x0e, 0x7f, 0x72, 0x0a, 0x71, 0x14, 0xd3, 0x73, 0x80, 0xba, 0xcd,
	0x4a, 0xb9, 0x7b, 0x79, 0xc3, 0x8e, 0xf9, 0x21, 0x89, 0xd7, 0xc2, 0x1f, 0x3a, 0x0f, 0xd8, 0xd1,
	0x33, 0xf0, 0xb5, 0x2c, 0xaa, 0xd4, 0xb4, 0x0d, 0x32, 0x18, 0xd8, 0x43, 0x23, 0x52, 0xe0, 0x89,
	0xf4, 0x93, 0xfe, 0x07, 0xaf, 0x1f, 0x26, 0x36, 0x54, 0x5f, 0xd2, 0xcd, 0x71, 0x8b, 0x89, 0x4d,
	0x03, 0xdc, 0x2d, 0xfc, 0x7c, 0xdc, 0x88, 0xc2, 0x34, 0x4f, 0x4d, 0x6a, 0x03, 0xaf, 0x85, 0xad,
	0xff, 0x30, 0xbc, 0x85, 0xe9, 0xa3, 0xca, 0xf1, 0xc7, 0x2d, 0xc8, 0xaf, 0x5b, 0x30, 0x58, 0xa4,
	0x79, 0xde, 0xa0, 0xd6, 0xe3, 0x99, 0x1c, 0x8c, 0x2e, 0x61, 0xd6, 0x4f, 0x6b, 0xba, 0x81, 0x59,
	0xd5, 0x17, 0x8c, 0x84, 0x5e, 0xbc, 0xda, 0xfe, 0xe3, 0xee, 0x0d, 0x79, 0xcf, 0x8b, 0x81, 0x8c,
	0x6e, 0x60, 0x7e, 0x67, 0x5f, 0x9a, 0x9e, 0xc0, 0x5c, 0xd7, 0xaa, 0x19, 0x07, 0x7c, 0x31, 0xa2,
	0xde, 0xaa, 0xc1, 0xf7, 0x16, 0xb5, 0xb1, 0x56, 0x4b, 0xe1, 0x60, 0x36, 0xb7, 0x7f, 0xbc, 0xfa,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0x68, 0xbb, 0xe5, 0xdc, 0x39, 0x02, 0x00, 0x00,
}
