// Code generated by protoc-gen-go.
// source: myc/protocol/misc.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	myc/protocol/misc.proto

It has these top-level messages:
	Hello
	Raw
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import version "gitlab.com/SporeDB/sporedb/db/version"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hello struct {
	Version  uint64 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Identity string `protobuf:"bytes,2,opt,name=identity" json:"identity,omitempty"`
}

func (m *Hello) Reset()                    { *m = Hello{} }
func (m *Hello) String() string            { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()               {}
func (*Hello) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Hello) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Hello) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type Raw struct {
	Key       string     `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Version   *version.V `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Data      []byte     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Signature []byte     `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Raw) Reset()                    { *m = Raw{} }
func (m *Raw) String() string            { return proto.CompactTextString(m) }
func (*Raw) ProtoMessage()               {}
func (*Raw) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Raw) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Raw) GetVersion() *version.V {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Raw) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Raw) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Hello)(nil), "protocol.Hello")
	proto.RegisterType((*Raw)(nil), "protocol.Raw")
}

func init() { proto.RegisterFile("myc/protocol/misc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x4e, 0xbf, 0xcf, 0x82, 0x30,
	0x10, 0x4d, 0x3f, 0xf8, 0x14, 0x4e, 0x07, 0x73, 0x8b, 0x0d, 0x71, 0x20, 0xc4, 0x81, 0x09, 0x12,
	0x9d, 0xdd, 0x9d, 0x3b, 0xb8, 0x17, 0x68, 0x4c, 0x23, 0x70, 0x06, 0xaa, 0x86, 0xff, 0xde, 0x50,
	0xad, 0x9d, 0xee, 0xfd, 0xb8, 0xf7, 0xee, 0x60, 0xdb, 0x4d, 0x75, 0x79, 0x1f, 0xc8, 0x50, 0x4d,
	0x6d, 0xd9, 0xe9, 0xb1, 0x2e, 0x2c, 0xc3, 0xc8, 0x89, 0x09, 0x6f, 0xaa, 0xf2, 0xa9, 0x86, 0x51,
	0x53, 0xef, 0xe6, 0x67, 0x27, 0x3b, 0xc1, 0xff, 0x59, 0xb5, 0x2d, 0x21, 0x87, 0xe5, 0xd7, 0xe1,
	0x2c, 0x65, 0x79, 0x28, 0x1c, 0xc5, 0x04, 0x22, 0xdd, 0xa8, 0xde, 0x68, 0x33, 0xf1, 0xbf, 0x94,
	0xe5, 0xb1, 0xf8, 0xf1, 0x8c, 0x20, 0x10, 0xf2, 0x85, 0x1b, 0x08, 0x6e, 0x6a, 0xb2, 0xc1, 0x58,
	0xcc, 0x10, 0xf7, 0xbe, 0x6e, 0xce, 0xac, 0x0e, 0x50, 0xb8, 0xc3, 0x17, 0x5f, 0x8d, 0x10, 0x36,
	0xd2, 0x48, 0x1e, 0xa4, 0x2c, 0x5f, 0x0b, 0x8b, 0x71, 0x07, 0xf1, 0xa8, 0xaf, 0xbd, 0x34, 0x8f,
	0x41, 0x71, 0xb0, 0x86, 0x17, 0xaa, 0x85, 0x7d, 0xfb, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x75,
	0x5b, 0x59, 0x6a, 0xf5, 0x00, 0x00, 0x00,
}
